### ISSUE TITLE
FIle Input

### ISSUE THREAD

**Issue by minasvisual** [ClassHP/md-crud#2]
hi, 
Congratulations in advance for the great pluigin. 
Im tring create a input field template but ng-model cannot set value on input.
How set value to input or directly in object row?

Thanks

**Comment by ClassHP** [comment]
Hello, if you show me a fragment of the code that you are implementing help me understand the problem you have.
I suppose what you need is to make a template with an input that has a behavior different from the one that comes by default in the library.
For that you can do the following:
```
<textarea ng-model="item.UserName" rows="4"></textarea>
```
Where "item" is the row that is being edited or inserted.
